#!/bin/bash

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

KERNEL_VERSION="6.18"
KERNEL_DIR="linux"
BUILD_DIR="$(pwd)/build"
OVERLAY_DIR="$(pwd)/overlay"

echo -e "${GREEN}=== ARM64 Linux Kernel + Buildroot Rootfs Builder for QEMU ===${NC}"
echo -e "${BLUE}Configuration: Optimized Tiny kernel + Buildroot rootfs${NC}"
echo ""

# Check dependencies
echo -e "${YELLOW}Checking dependencies...${NC}"
for cmd in wget tar make gcc flex bison bc git rsync e2fsck tune2fs; do
        if ! command -v $cmd &> /dev/null; then
                echo -e "${RED}ERROR: $cmd is not installed${NC}"
                exit 1
        fi
done

# ============================================================================
# PART 0: Create Overlay Directory with Network Setup
# ============================================================================

echo -e "${YELLOW}Creating network overlay...${NC}"

mkdir -p "$OVERLAY_DIR/etc/init.d"
mkdir -p "$OVERLAY_DIR/etc/network"

# Create ifupdown network interfaces configuration
cat > "$OVERLAY_DIR/etc/network/interfaces" << 'EOF'
# Network interface configuration
auto lo
iface lo inet loopback

# DHCP on eth0
auto eth0
iface eth0 inet dhcp
EOF

# Create network init script
cat > "$OVERLAY_DIR/etc/init.d/S40network" << 'EOF'
#!/bin/sh

case "$1" in
  start)
    echo "Starting networking..."
    # Wait for interface to appear
    for i in $(seq 1 10); do
      if [ -d /sys/class/net/eth0 ]; then
        break
      fi
      sleep 1
    done
    # Bring up loopback
    /sbin/ip link set lo up
    /sbin/ip addr add 127.0.0.1/8 dev lo
    # Bring up eth0 with DHCP
    if [ -x /sbin/ifup ]; then
      /sbin/ifup eth0
    else
      echo "Bringing up eth0 with dhcpcd..."
      /sbin/dhcpcd eth0 -t 30
    fi
    ;;
  stop)
    echo "Stopping networking..."
    if [ -x /sbin/ifdown ]; then
      /sbin/ifdown -a
    else
      /sbin/dhcpcd -x eth0 2>/dev/null || true
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
exit 0
EOF

chmod +x "$OVERLAY_DIR/etc/init.d/S40network"

# Create resolv.conf template (will be generated by dhcpcd)
mkdir -p "$OVERLAY_DIR/etc"
cat > "$OVERLAY_DIR/etc/resolv.conf" << 'EOF'
# This file is automatically populated by dhcpcd
# nameserver 8.8.8.8
# nameserver 8.8.4.4
EOF

echo -e "${GREEN}✓ Overlay created${NC}"

# ============================================================================
# PART 1: Build Custom Kernel
# ============================================================================

echo ""
echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}PART 1: Building Custom Kernel ${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"

if [ ! -d "$KERNEL_DIR" ]; then
        echo -e "${YELLOW}Cloning Linux kernel ${KERNEL_VERSION}...${NC}"
        git clone --depth=1 --branch=v${KERNEL_VERSION} git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
else
        echo -e "${YELLOW}Kernel source already exists${NC}"
fi

cd "$KERNEL_DIR"

echo -e "${YELLOW}Configuring kernel...${NC}"
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- tinyconfig

# Core features
./scripts/config --enable CONFIG_64BIT
./scripts/config --enable CONFIG_ARM64
./scripts/config --enable CONFIG_SMP
./scripts/config --set-val CONFIG_NR_CPUS 4

# Console
./scripts/config --enable CONFIG_TTY
./scripts/config --enable CONFIG_SERIAL_AMBA_PL011
./scripts/config --enable CONFIG_SERIAL_AMBA_PL011_CONSOLE
./scripts/config --enable CONFIG_HW_CONSOLE
./scripts/config --enable CONFIG_VT
./scripts/config --enable CONFIG_VT_CONSOLE
./scripts/config --enable CONFIG_UNIX98_PTYS

# VIRTIO
./scripts/config --enable CONFIG_VIRTIO
./scripts/config --enable CONFIG_VIRTIO_MMIO
./scripts/config --enable CONFIG_VIRTIO_BLK
./scripts/config --enable CONFIG_VIRTIO_BLK_SCSI
./scripts/config --enable CONFIG_VIRTIO_NET
./scripts/config --enable CONFIG_VIRTIO_CONSOLE
./scripts/config --enable CONFIG_VIRTIO_ANCHOR
./scripts/config --enable CONFIG_VIRTIO_QUEUE_RESET

# Block devices
./scripts/config --enable CONFIG_BLK_DEV
./scripts/config --enable CONFIG_BLOCK
./scripts/config --enable CONFIG_HAVE_EFFICIENT_UNALIGNED_ACCESS
./scripts/config --enable CONFIG_BLK_DEV_INITRD
./scripts/config --enable CONFIG_BLK_DEV_RAM

# Filesystems
./scripts/config --enable CONFIG_EXT4_FS
./scripts/config --enable CONFIG_EXT4_USE_FOR_EXT2
./scripts/config --enable CONFIG_EXT3_FS
./scripts/config --enable CONFIG_EXT2_FS
./scripts/config --enable CONFIG_TMPFS
./scripts/config --enable CONFIG_DEVTMPFS
./scripts/config --enable CONFIG_DEVTMPFS_MOUNT

# Kernel features
./scripts/config --enable CONFIG_PROC_FS
./scripts/config --enable CONFIG_SYSFS
./scripts/config --enable CONFIG_MMU
./scripts/config --enable CONFIG_PRINTK
./scripts/config --enable CONFIG_EARLY_PRINTK

# Network
./scripts/config --enable CONFIG_NET
./scripts/config --enable CONFIG_INET
./scripts/config --enable CONFIG_PACKET
./scripts/config --enable CONFIG_UNIX

# Devices
./scripts/config --enable CONFIG_PCI
./scripts/config --enable CONFIG_PCI_HOST_GENERIC
./scripts/config --enable CONFIG_RTC_CLASS
./scripts/config --enable CONFIG_RTC_DRV_PL031
./scripts/config --enable CONFIG_GPIOLIB
./scripts/config --enable CONFIG_GENERIC_IRQ_INJECTION
./scripts/config --enable CONFIG_IRQCHIP

# Execution
./scripts/config --enable CONFIG_BINFMT_ELF
./scripts/config --enable CONFIG_BINFMT_SCRIPT

# System
./scripts/config --enable CONFIG_PM
./scripts/config --enable CONFIG_FRAMEBUFFER_CONSOLE
./scripts/config --enable CONFIG_FB
./scripts/config --enable CONFIG_INPUT
./scripts/config --enable CONFIG_INPUT_KEYBOARD
./scripts/config --enable CONFIG_INPUT_MOUSE
./scripts/config --enable CONFIG_HAVE_SMP

# Futex support
./scripts/config --enable CONFIG_FUTEX
./scripts/config --enable CONFIG_FUTEX_PI

# ============================================================================
# Performance Tuning
# ============================================================================

echo -e "${YELLOW}Applying performance tuning...${NC}"

# Scheduler
./scripts/config --enable CONFIG_HIGH_RES_TIMERS
./scripts/config --enable CONFIG_HZ_1000
./scripts/config --disable CONFIG_HZ_250

# I/O
./scripts/config --enable CONFIG_MQ_IOSCHED_DEADLINE
./scripts/config --enable CONFIG_MQ_IOSCHED_KYBER
./scripts/config --set-str CONFIG_DEFAULT_IOSCHED "kyber"

# CPU Freq
./scripts/config --enable CONFIG_CPU_FREQ
./scripts/config --enable CONFIG_CPU_FREQ_GOV_POWERSAVE
./scripts/config --enable CONFIG_CPU_FREQ_GOV_PERFORMANCE
./scripts/config --enable CONFIG_CPU_FREQ_GOV_SCHEDUTIL
./scripts/config --set-str CONFIG_CPU_FREQ_DEFAULT_GOV "schedutil"

# Scheduling
./scripts/config --enable CONFIG_SCHED_EEVDF
./scripts/config --disable CONFIG_NO_HZ_FULL
./scripts/config --enable CONFIG_PREEMPT
./scripts/config --disable CONFIG_PREEMPT_NONE
./scripts/config --disable CONFIG_PREEMPT_VOLUNTARY

# Hardening
./scripts/config --enable CONFIG_STACK_VALIDATION
./scripts/config --enable CONFIG_RETPOLINE
./scripts/config --disable CONFIG_RETPOLINE_LFENCE
./scripts/config --enable CONFIG_PAGE_TABLE_ISOLATION

# Task scheduling
./scripts/config --enable CONFIG_SCHED_DEBUG
./scripts/config --enable CONFIG_SCHED_AUTOGROUP
./scripts/config --set-str CONFIG_RCU_IMPLEMENTATION "tree"
./scripts/config --enable CONFIG_RCU_FAST_NO_HZ
./scripts/config --enable CONFIG_SCHED_DEADLINE

# Memory
./scripts/config --enable CONFIG_SWAP
./scripts/config --enable CONFIG_TRANSPARENT_HUGEPAGE
./scripts/config --set-str CONFIG_TRANSPARENT_HUGEPAGE_DEFRAG "defer+madvise"
./scripts/config --enable CONFIG_COMPACTION
./scripts/config --enable CONFIG_MIGRATION

# Network
./scripts/config --enable CONFIG_TCP_CONG_CUBIC
./scripts/config --set-str CONFIG_DEFAULT_TCP_CONG "cubic"
./scripts/config --enable CONFIG_SYN_COOKIES
./scripts/config --enable CONFIG_AIO
./scripts/config --enable CONFIG_HUGETLBFS
./scripts/config --enable CONFIG_HUGETLB_PAGE
./scripts/config --enable CONFIG_HOTPLUG_CPU

echo -e "${YELLOW}Building kernel...${NC}"
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- olddefconfig
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j"$(nproc)"

mkdir -p "$BUILD_DIR"
cp arch/arm64/boot/Image "$BUILD_DIR/"
KERNEL_SIZE=$(ls -lh "$BUILD_DIR/Image" | awk '{print $5}')
echo -e "${GREEN}✓ Kernel built: $KERNEL_SIZE${NC}"

cd ..

# ============================================================================
# PART 2: Build Rootfs with Buildroot
# ============================================================================

echo ""
echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}PART 2: Building Rootfs with Buildroot${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"

if [ ! -d "buildroot" ]; then
        echo -e "${YELLOW}Cloning Buildroot...${NC}"
        git clone --depth=1 https://git.buildroot.net/buildroot
fi

cd buildroot

echo -e "${YELLOW}Loading tinynix defconfig...${NC}"
cp ../tinynix_defconfig .
make BR2_DEFCONFIG=tinynix_defconfig defconfig

# Add overlay to bring in network scripts
echo "BR2_ROOTFS_OVERLAY=$OVERLAY_DIR" >> .config

echo -e "${YELLOW}Building Buildroot (this takes 20-40 minutes)...${NC}"
make -j"$(nproc)"

# Verify
if [ ! -f "output/images/rootfs.ext2" ]; then
        echo -e "${RED}ERROR: Rootfs not found!${NC}"
        exit 1
fi

ROOTFS_SIZE=$(ls -lh output/images/rootfs.ext2 | awk '{print $5}')
echo -e "${GREEN}✓ Rootfs built: $ROOTFS_SIZE${NC}"
cp output/images/rootfs.ext2 "$BUILD_DIR/rootfs.ext4"

cd ..

# ============================================================================
# PART 3: Launch QEMU
# ============================================================================

echo ""
echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}PART 3: Launching QEMU${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"

KERNEL="build/Image"
ROOTFS="build/rootfs.ext4"

if [ ! -f "$KERNEL" ] || [ ! -f "$ROOTFS" ]; then
        echo -e "${RED}ERROR: Missing files!${NC}"
        exit 1
fi

KERNEL_SIZE=$(ls -lh "$KERNEL" | awk '{print $5}')
ROOTFS_SIZE=$(ls -lh "$ROOTFS" | awk '{print $5}')

echo ""
echo -e "${GREEN}Build Complete!${NC}"
echo ""
echo -e "${YELLOW}System Configuration:${NC}"
echo "  Kernel:        $KERNEL_SIZE (6.18 optimized)"
echo "  Rootfs:        $ROOTFS_SIZE (Buildroot with full networking)"
echo "  Architecture:  ARM64 (Cortex-A53)"
echo "  RAM:           1 GB"
echo "  Networking:    DHCP on eth0 + SSH (port 2222)"
echo ""
echo -e "${YELLOW}Boot & Test Network:${NC}"
echo "  Inside QEMU:"
echo "    # ip addr                 - Show eth0 IP (auto-assigned)"
echo "    # ping 8.8.8.8            - Test internet"
echo "    # wget https://google.com - Download files"
echo "    # exit                    - Leave shell"
echo ""
echo "  From host:"
echo "    ssh -p 2222 root@127.0.0.1"
echo ""

qemu-system-aarch64 \
        -M virt \
        -cpu cortex-a53 \
        -nographic \
        -smp 2 \
        -m 1024M \
        -kernel "$KERNEL" \
        -append "root=/dev/vda rw console=ttyAMA0" \
        -drive file="$ROOTFS",if=virtio,format=raw \
        -netdev user,id=net0,hostfwd=tcp::2222-:22 \
        -device virtio-net-device,netdev=net0